spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-1111
    - (915) 382-1111