spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "{cipher}58e867ce72c3207b3bc87240529949f19c05310c8473fcf1cbc415e73ab0950a78d8c20e2470c6e292c29642fd7fe06c"
  onCallSupport:
    - (412) 419-1111
    - (915) 382-1111
