spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "{cipher}f8f8be5906864522195e57e18f54064a07528d305c1995d2b4fe29712d3d3d725fb199aa3f53d55534d011531078650c"
  onCallSupport:
    - (412) 419-1111
    - (915) 382-1111
