spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "2.4"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-2222
    - (915) 382-2222